import Home from '@/src/Components/Home/Home/Home'
import RootLayout from '@/src/Layouts/RootLayout'
import Head from 'next/head'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>DAPS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <h1 className='font-thin text-sm top-0 bg-[#EFF4F7] text-center py-2 '>Go extra on celebrations & saving with <strong className='font-bold'>Bond with Dav</strong>Bag <strong className='font-bold'>offers</strong> & personalized gifts.</h1>
      <RootLayout>
        <Home />
      </RootLayout>
    </>
  )
}
